### ISSUE TITLE
An error has occured

### ISSUE THREAD

**Issue by lgte70** [William04A/pispeedtest#8]
Hi,
I think I have managed to follow all instructions, but when executing the mainprogram it just shows a Windows pop-up "PiSpeedtest - An error has occured". This is my input and output in the command shell:
![Skärmklipp](https://user-images.githubusercontent.com/74054151/98365326-895d9f80-2032-11eb-82fc-54fa5c1bba46.PNG)

E:\>cd code\pispeedtest

E:\code\pispeedtest>mainprogram.py
PiSpeedtest 5.5.
Language configuration en-us found.

**Comment by William04A** [comment]
Hi Igte - so sorry about the long overdue response! I have switched GitHub accounts since this was one of my first coding projects ever. If you are still looking into using PiSpeedtest, I can review and patch a fix for you :)

But first question - are you using Windows? PiSpeedtest requires Windows at the moment.

Second - all dependencies installed?

**Comment by lgte70** [comment]
Hi William. Thank you for answering. I eventually sorted it out, but forgot to remove the post.

**Comment by William04A** [comment]
No problem - cool that you fixed it and super cool that you were interested in a very old repository of mine!

If you are interested in what I do nowadays and how much my coding has improved, :P, you should check out my new account @sotpotatis!
